##Завантаження даних##

In [1]:
import pandas as pd
import numpy as np
from google.colab import drive

In [2]:
drive.mount('/gdrive')
%cd /gdrive
path = '/gdrive/My Drive/Colab Notebooks/Datafiles/Hepatitis/hepatitis.data'
names = ['Class', 'AGE', 'SEX', 'STEROID', 'ANTIVIRALS', 'FATIGUE', 'MALAISE', 'ANOREXIA',
         'LIVER BIG', 'LIVER FIRM', 'SPLEEN PALPABLE', 'SPIDERS', 'ASCITES', 'VARICES',
         'BILIRUBIN', 'ALK PHOSPHATE', 'SGOT', 'ALBUMIN', 'PROTIME', 'HISTOLOGY']

data = pd.read_csv(path, names=names, header=None)
data

Drive already mounted at /gdrive; to attempt to forcibly remount, call drive.mount("/gdrive", force_remount=True).
/gdrive


Class  AGE  SEX STEROID  ...  SGOT ALBUMIN PROTIME HISTOLOGY
0        2   30    2       1  ...    18     4.0       ?         1
1        2   50    1       1  ...    42     3.5       ?         1
2        2   78    1       2  ...    32     4.0       ?         1
3        2   31    1       ?  ...    52     4.0      80         1
4        2   34    1       2  ...   200     4.0       ?         1
..     ...  ...  ...     ...  ...   ...     ...     ...       ...
150      1   46    1       2  ...   242     3.3      50         2
151      2   44    1       2  ...   142     4.3       ?         2
152      2   61    1       1  ...    20     4.1       ?         2
153      2   53    2       1  ...    19     4.1      48         2
154      1   43    1       2  ...    19     3.1      42         2

[155 rows x 20 columns]

##Обробка даних##

Спочатку перевіримо на наявність відсутніх значень.

In [3]:
data.isna().sum()

Class              0
AGE                0
SEX                0
STEROID            0
ANTIVIRALS         0
FATIGUE            0
MALAISE            0
ANOREXIA           0
LIVER BIG          0
LIVER FIRM         0
SPLEEN PALPABLE    0
SPIDERS            0
ASCITES            0
VARICES            0
BILIRUBIN          0
ALK PHOSPHATE      0
SGOT               0
ALBUMIN            0
PROTIME            0
HISTOLOGY          0
dtype: int64

In [4]:
for name in names:
  print(data[name].unique())

[2 1]
[30 50 78 31 34 51 23 39 32 41 47 38 66 40 22 27 42 25 49 58 61 62 26 35
 37 20 65 52 33 56 28 36 44 64 45 57 24 67 59 60 48 54  7 69 72 70 46 53
 43]
[2 1]
['1' '2' '?']
[2 1]
['2' '1' '?']
['2' '1' '?']
['2' '1' '?']
['1' '2' '?']
['2' '1' '?']
['2' '1' '?']
['2' '1' '?']
['2' '1' '?']
['2' '?' '1']
['1.00' '0.90' '0.70' '?' '1.30' '2.20' '2.00' '1.20' '0.60' '0.40' '0.80'
 '1.40' '2.30' '0.50' '0.30' '4.60' '1.80' '3.50' '4.10' '1.60' '2.80'
 '1.50' '2.50' '3.00' '4.80' '2.40' '1.70' '1.10' '3.20' '2.90' '8.00'
 '3.90' '1.90' '4.20' '7.60']
['85' '135' '96' '46' '?' '95' '78' '59' '81' '57' '72' '102' '62' '53'
 '70' '48' '133' '60' '45' '175' '280' '58' '67' '194' '150' '180' '75'
 '56' '71' '74' '80' '191' '125' '110' '50' '92' '52' '26' '215' '164'
 '103' '34' '68' '82' '127' '76' '100' '55' '167' '30' '179' '141' '44'
 '165' '118' '230' '107' '40' '147' '114' '84' '123' '168' '86' '138'
 '155' '63' '256' '119' '139' '90' '160' '158' '115' '243' '181' '130'
 '166' '295' '12

Відсутніх значень немає, але видно що у таблиці є "?". Для розуміння того що робити далі треба перевірити скільки їх взагалі і де вони є.

In [5]:
for name in names:
  print(name)
  print(data[data[name]=='?'])

Class
Empty DataFrame
Columns: [Class, AGE, SEX, STEROID, ANTIVIRALS, FATIGUE, MALAISE, ANOREXIA, LIVER BIG, LIVER FIRM, SPLEEN PALPABLE, SPIDERS, ASCITES, VARICES, BILIRUBIN, ALK PHOSPHATE, SGOT, ALBUMIN, PROTIME, HISTOLOGY]
Index: []
AGE
Empty DataFrame
Columns: [Class, AGE, SEX, STEROID, ANTIVIRALS, FATIGUE, MALAISE, ANOREXIA, LIVER BIG, LIVER FIRM, SPLEEN PALPABLE, SPIDERS, ASCITES, VARICES, BILIRUBIN, ALK PHOSPHATE, SGOT, ALBUMIN, PROTIME, HISTOLOGY]
Index: []
SEX
Empty DataFrame
Columns: [Class, AGE, SEX, STEROID, ANTIVIRALS, FATIGUE, MALAISE, ANOREXIA, LIVER BIG, LIVER FIRM, SPLEEN PALPABLE, SPIDERS, ASCITES, VARICES, BILIRUBIN, ALK PHOSPHATE, SGOT, ALBUMIN, PROTIME, HISTOLOGY]
Index: []
STEROID
   Class  AGE  SEX STEROID  ...  SGOT ALBUMIN PROTIME HISTOLOGY
3      2   31    1       ?  ...    52     4.0      80         1

[1 rows x 20 columns]
ANTIVIRALS
Empty DataFrame
Columns: [Class, AGE, SEX, STEROID, ANTIVIRALS, FATIGUE, MALAISE, ANOREXIA, LIVER BIG, LIVER FIRM, SPLEEN PALP

Як ми бачимо, є три типи поганих даних. Перший, це рядки в яких просто відсутня більша кількість інформації, а саме 6,7, 14, 31, 41, 56, 72, 83, 118, 147. Колонка "PROTIME" по якій половина даних відсутня, та колонки в яких відсутня не критична кількість даних і ці дані можна замінити модою. Почнемо з видалення поганих рядків.

In [6]:
data1 = data.drop([6 , 7, 14, 31, 41, 56, 72, 83, 118, 147])

In [7]:
for name in names:
  print(name)
  print(data1[data1[name]=='?'])

Class
Empty DataFrame
Columns: [Class, AGE, SEX, STEROID, ANTIVIRALS, FATIGUE, MALAISE, ANOREXIA, LIVER BIG, LIVER FIRM, SPLEEN PALPABLE, SPIDERS, ASCITES, VARICES, BILIRUBIN, ALK PHOSPHATE, SGOT, ALBUMIN, PROTIME, HISTOLOGY]
Index: []
AGE
Empty DataFrame
Columns: [Class, AGE, SEX, STEROID, ANTIVIRALS, FATIGUE, MALAISE, ANOREXIA, LIVER BIG, LIVER FIRM, SPLEEN PALPABLE, SPIDERS, ASCITES, VARICES, BILIRUBIN, ALK PHOSPHATE, SGOT, ALBUMIN, PROTIME, HISTOLOGY]
Index: []
SEX
Empty DataFrame
Columns: [Class, AGE, SEX, STEROID, ANTIVIRALS, FATIGUE, MALAISE, ANOREXIA, LIVER BIG, LIVER FIRM, SPLEEN PALPABLE, SPIDERS, ASCITES, VARICES, BILIRUBIN, ALK PHOSPHATE, SGOT, ALBUMIN, PROTIME, HISTOLOGY]
Index: []
STEROID
   Class  AGE  SEX STEROID  ...  SGOT ALBUMIN PROTIME HISTOLOGY
3      2   31    1       ?  ...    52     4.0      80         1

[1 rows x 20 columns]
ANTIVIRALS
Empty DataFrame
Columns: [Class, AGE, SEX, STEROID, ANTIVIRALS, FATIGUE, MALAISE, ANOREXIA, LIVER BIG, LIVER FIRM, SPLEEN PALP

Стало набагато краще, тепер видалимо колонку "PROTIME".

In [8]:
del data1["PROTIME"]


In [9]:
names.pop(18)

'PROTIME'

In [10]:
for name in names:
  print(name)
  print(data1[data1[name]=='?'])

Class
Empty DataFrame
Columns: [Class, AGE, SEX, STEROID, ANTIVIRALS, FATIGUE, MALAISE, ANOREXIA, LIVER BIG, LIVER FIRM, SPLEEN PALPABLE, SPIDERS, ASCITES, VARICES, BILIRUBIN, ALK PHOSPHATE, SGOT, ALBUMIN, HISTOLOGY]
Index: []
AGE
Empty DataFrame
Columns: [Class, AGE, SEX, STEROID, ANTIVIRALS, FATIGUE, MALAISE, ANOREXIA, LIVER BIG, LIVER FIRM, SPLEEN PALPABLE, SPIDERS, ASCITES, VARICES, BILIRUBIN, ALK PHOSPHATE, SGOT, ALBUMIN, HISTOLOGY]
Index: []
SEX
Empty DataFrame
Columns: [Class, AGE, SEX, STEROID, ANTIVIRALS, FATIGUE, MALAISE, ANOREXIA, LIVER BIG, LIVER FIRM, SPLEEN PALPABLE, SPIDERS, ASCITES, VARICES, BILIRUBIN, ALK PHOSPHATE, SGOT, ALBUMIN, HISTOLOGY]
Index: []
STEROID
   Class  AGE  SEX STEROID  ...  ALK PHOSPHATE SGOT ALBUMIN HISTOLOGY
3      2   31    1       ?  ...             46   52     4.0         1

[1 rows x 19 columns]
ANTIVIRALS
Empty DataFrame
Columns: [Class, AGE, SEX, STEROID, ANTIVIRALS, FATIGUE, MALAISE, ANOREXIA, LIVER BIG, LIVER FIRM, SPLEEN PALPABLE, SPIDERS, 

Тепер замінимо відсутні дискретні значення модою, а неперервні сердніми. 

In [11]:
data1['STEROID'][data1['STEROID']=='?'] = data1['STEROID'].mode()[0]
data1['LIVER BIG'][data1['LIVER BIG']=='?'] = data1['LIVER BIG'].mode()[0]
data1['LIVER FIRM'][data1['LIVER FIRM']=='?'] = data1['LIVER FIRM'].mode()[0]
data1

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid 

Class  AGE  SEX STEROID  ...  ALK PHOSPHATE SGOT ALBUMIN HISTOLOGY
0        2   30    2       1  ...             85   18     4.0         1
1        2   50    1       1  ...            135   42     3.5         1
2        2   78    1       2  ...             96   32     4.0         1
3        2   31    1       2  ...             46   52     4.0         1
4        2   34    1       2  ...              ?  200     4.0         1
..     ...  ...  ...     ...  ...            ...  ...     ...       ...
150      1   46    1       2  ...              ?  242     3.3         2
151      2   44    1       2  ...            126  142     4.3         2
152      2   61    1       1  ...             75   20     4.1         2
153      2   53    2       1  ...             81   19     4.1         2
154      1   43    1       2  ...            100   19     3.1         2

[145 rows x 19 columns]

In [12]:
for name in names:
  print(name)
  print(data1[data1[name]=='?'])

Class
Empty DataFrame
Columns: [Class, AGE, SEX, STEROID, ANTIVIRALS, FATIGUE, MALAISE, ANOREXIA, LIVER BIG, LIVER FIRM, SPLEEN PALPABLE, SPIDERS, ASCITES, VARICES, BILIRUBIN, ALK PHOSPHATE, SGOT, ALBUMIN, HISTOLOGY]
Index: []
AGE
Empty DataFrame
Columns: [Class, AGE, SEX, STEROID, ANTIVIRALS, FATIGUE, MALAISE, ANOREXIA, LIVER BIG, LIVER FIRM, SPLEEN PALPABLE, SPIDERS, ASCITES, VARICES, BILIRUBIN, ALK PHOSPHATE, SGOT, ALBUMIN, HISTOLOGY]
Index: []
SEX
Empty DataFrame
Columns: [Class, AGE, SEX, STEROID, ANTIVIRALS, FATIGUE, MALAISE, ANOREXIA, LIVER BIG, LIVER FIRM, SPLEEN PALPABLE, SPIDERS, ASCITES, VARICES, BILIRUBIN, ALK PHOSPHATE, SGOT, ALBUMIN, HISTOLOGY]
Index: []
STEROID
Empty DataFrame
Columns: [Class, AGE, SEX, STEROID, ANTIVIRALS, FATIGUE, MALAISE, ANOREXIA, LIVER BIG, LIVER FIRM, SPLEEN PALPABLE, SPIDERS, ASCITES, VARICES, BILIRUBIN, ALK PHOSPHATE, SGOT, ALBUMIN, HISTOLOGY]
Index: []
ANTIVIRALS
Empty DataFrame
Columns: [Class, AGE, SEX, STEROID, ANTIVIRALS, FATIGUE, MALAISE, A

Тепер замінимо середніми.

In [13]:
for column in data1[['BILIRUBIN', 'ALK PHOSPHATE', 'ALBUMIN']]:
  df1 = data1[column][data1[column] != '?']
  df2 = df1.apply(pd.to_numeric)
  data1[column].replace('?', df2.mean(), inplace = True)


In [14]:
for name in names:
  print(name)
  print(data1[data1[name]=='?'])
data1

Class
Empty DataFrame
Columns: [Class, AGE, SEX, STEROID, ANTIVIRALS, FATIGUE, MALAISE, ANOREXIA, LIVER BIG, LIVER FIRM, SPLEEN PALPABLE, SPIDERS, ASCITES, VARICES, BILIRUBIN, ALK PHOSPHATE, SGOT, ALBUMIN, HISTOLOGY]
Index: []
AGE
Empty DataFrame
Columns: [Class, AGE, SEX, STEROID, ANTIVIRALS, FATIGUE, MALAISE, ANOREXIA, LIVER BIG, LIVER FIRM, SPLEEN PALPABLE, SPIDERS, ASCITES, VARICES, BILIRUBIN, ALK PHOSPHATE, SGOT, ALBUMIN, HISTOLOGY]
Index: []
SEX
Empty DataFrame
Columns: [Class, AGE, SEX, STEROID, ANTIVIRALS, FATIGUE, MALAISE, ANOREXIA, LIVER BIG, LIVER FIRM, SPLEEN PALPABLE, SPIDERS, ASCITES, VARICES, BILIRUBIN, ALK PHOSPHATE, SGOT, ALBUMIN, HISTOLOGY]
Index: []
STEROID
Empty DataFrame
Columns: [Class, AGE, SEX, STEROID, ANTIVIRALS, FATIGUE, MALAISE, ANOREXIA, LIVER BIG, LIVER FIRM, SPLEEN PALPABLE, SPIDERS, ASCITES, VARICES, BILIRUBIN, ALK PHOSPHATE, SGOT, ALBUMIN, HISTOLOGY]
Index: []
ANTIVIRALS
Empty DataFrame
Columns: [Class, AGE, SEX, STEROID, ANTIVIRALS, FATIGUE, MALAISE, A

Class  AGE  SEX STEROID  ...  ALK PHOSPHATE SGOT ALBUMIN HISTOLOGY
0        2   30    2       1  ...             85   18     4.0         1
1        2   50    1       1  ...            135   42     3.5         1
2        2   78    1       2  ...             96   32     4.0         1
3        2   31    1       2  ...             46   52     4.0         1
4        2   34    1       2  ...        105.336  200     4.0         1
..     ...  ...  ...     ...  ...            ...  ...     ...       ...
150      1   46    1       2  ...        105.336  242     3.3         2
151      2   44    1       2  ...            126  142     4.3         2
152      2   61    1       1  ...             75   20     4.1         2
153      2   53    2       1  ...             81   19     4.1         2
154      1   43    1       2  ...            100   19     3.1         2

[145 rows x 19 columns]

Тепер трансформуємо усе у неперервні величини.

In [15]:
data1 = data1.apply(pd.to_numeric)
for name in names:
  print(data1[name].unique())

[2 1]
[30 50 78 31 34 39 32 41 38 66 40 22 27 42 25 49 58 61 51 26 35 37 23 20
 65 52 33 56 28 36 44 64 45 57 24 62 59 47 60 48 54  7 69 72 46 53 43]
[2 1]
[1 2]
[2 1]
[2 1]
[2 1]
[2 1]
[1 2]
[2 1]
[2 1]
[2 1]
[2 1]
[2 1]
[1.         0.9        0.7        1.3        2.2        2.
 1.2        0.6        0.4        0.8        1.4        2.3
 0.5        0.3        1.41258741 1.8        3.5        4.1
 1.6        2.8        1.5        2.5        4.6        3.
 4.8        2.4        1.7        1.1        3.2        2.9
 8.         3.9        1.9        4.2        7.6       ]
[ 85.         135.          96.          46.         105.33606557
  95.          78.          59.          81.          57.
  72.         102.          62.          53.          70.
  48.         133.          60.          45.         175.
 280.          58.          67.         194.         150.
 180.          75.          71.          74.          80.
 191.         125.         110.          50.          92.
  52.    

##Розділення даних##

In [16]:

from sklearn.model_selection import train_test_split

In [17]:
X = data1.drop(['Class'], axis=1)
y = data1['Class']
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=20)

X_train

AGE  SEX  STEROID  ANTIVIRALS  ...  ALK PHOSPHATE  SGOT   ALBUMIN  HISTOLOGY
61    32    1        2           2  ...     102.000000    64  4.000000          1
108   54    1        1           1  ...     155.000000   225  3.600000          2
80    23    1        2           2  ...     105.336066    14  4.800000          1
1     50    1        1           2  ...     135.000000    42  3.500000          1
122   42    1        2           2  ...      85.000000    40  3.821481          2
..   ...  ...      ...         ...  ...            ...   ...       ...        ...
25    27    1        1           2  ...      95.000000    46  3.800000          1
82    30    1        1           2  ...     100.000000    31  4.000000          1
146   41    1        2           2  ...      65.000000   120  3.400000          2
18    38    1        2           2  ...      53.000000    42  4.100000          2
107   45    1        1           2  ...     105.336066   648  3.821481          2

[116 rows x 18 columns]

##Вибираємо модель##

In [18]:
from sklearn.metrics import accuracy_score
models =[]

In [19]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(max_iter=1000)
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print('LogisticRegression: ', accuracy_score(y_test,y_pred)*100)
models.append(['LogisticRegression: ',accuracy_score(y_test,y_pred)*100])

LogisticRegression:  86.20689655172413


In [20]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(3)
model.fit(X_train, y_train)
train_predictions = model.predict(X_test)
y_pred=model.predict(X_test)
print('KNN3: ', accuracy_score(y_test,y_pred)*100)
models.append(['KNN3 ',accuracy_score(y_test,y_pred)*100])

KNN3:  68.96551724137932


In [21]:
model = KNeighborsClassifier(4)
model.fit(X_train, y_train)
train_predictions = model.predict(X_test)
y_pred=model.predict(X_test)
print('KNN4: ', accuracy_score(y_test,y_pred)*100)
models.append(['KNN4 ',accuracy_score(y_test,y_pred)*100])

KNN4:  58.620689655172406


In [22]:
from xgboost import XGBClassifier
model = XGBClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print('XGBClassifier: ', accuracy_score(y_test,y_pred)*100)
models.append(['XGBClassifier: ',accuracy_score(y_test,y_pred)*100])

XGBClassifier:  86.20689655172413


In [23]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(n_estimators=50, random_state=42)
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print('RandomForestClassifier: ', accuracy_score(y_test,y_pred)*100)
models.append(['RandomForestClassifier: ',accuracy_score(y_test,y_pred)*100])

RandomForestClassifier:  86.20689655172413


In [24]:
from sklearn.svm import SVC
model = SVC()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print('SVC: ', accuracy_score(y_test,y_pred)*100)
models.append(['SVC: ',accuracy_score(y_test,y_pred)*100])

SVC:  75.86206896551724


In [25]:
models

[['LogisticRegression: ', 86.20689655172413],
 ['KNN3 ', 68.96551724137932],
 ['KNN4 ', 58.620689655172406],
 ['XGBClassifier: ', 86.20689655172413],
 ['RandomForestClassifier: ', 86.20689655172413],
 ['SVC: ', 75.86206896551724]]

Як ми бачимо, найкращі результати ми отримали за допомогою моделі XGBoost та RandomForest, тому для данної задачі підійдуть моделі які мають у основі дерева.